README.md, src/ComponentPage.js, src/styles/App.scss
And remove unnecessary import and sidebar entry to avoid confusion.
=> Clean up README

README.md, src/ComponentPage.js, src/HeaderBar.js
- Icon link in HeaderBar
- Link in Sidebar
=> Fix broken links

README.md, package-lock.json, package.json, src/App.js, src/ButtonPage.js, src/HeaderBar.js, src/styles/HeaderBar.scss
=> fix: style and font for header component

src/App.js, src/HeaderBar.js
Fixes error when testing from http://localhost:3000/
=> Don't rely on absolute URL for header logic

README.md, src/App.js, src/ButtonPage.js, src/styles/App.scss
Also use the uncompiled mode modules for JS it isn't a performance issue (unlike CSS compilation).
=> Add ripples to landing page

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json, src/App.js, src/ComponentPage.js, src/FabPage.js, src/images/floating_action_button_180px.svg, src/styles/FabPage.scss
fixes #24 
NOTE: I edited the Landing page SVG. It had an extended FAB in the image, but we currently don't support that. I made the SVG look like it does in the Landing page mock: https://gallery.googleplex.com/projects/MCHbtQVoQ2HCZToS_wX_kMCN/files/MCHtA7U1iMGr6_KZPshJxIAhD0opuTKYyuk
=> feat: Add floating action button page

config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, src/App.js, src/ComponentPage.js, src/LinearProgressIndicatorPage.js, src/images/linear_progress_180px.svg, src/styles/LinearProgressIndicatorPage.scss
=> feat: Add linear progress indicator page

package-lock.json, package.json, src/ComponentImageList.js, src/ComponentPage.js, src/ComponentSidebar.js, src/TabsCatalog.js, src/images/fonts_180px.svg, src/images/tabs_180px.svg, src/styles/TabsCatalog.scss
=> feat(tabs): Add demo

src/ButtonCatalog.js, src/CardCatalog.js, src/CheckboxCatalog.js, src/ChipsCatalog.js, src/DialogCatalog.js, src/DrawerCatalog.js, src/ElevationCatalog.js, src/FabCatalog.js, src/IconToggleCatalog.js, src/LinearProgressIndicatorCatalog.js, src/ListCatalog.js, src/MenuCatalog.js, src/RadioButtonCatalog.js, src/RippleCatalog.js, src/SelectCatalog.js, src/SliderCatalog.js, src/SnackbarCatalog.js, src/SwitchCatalog.js, src/TextFieldCatalog.js, src/TopAppBarCatalog.js, src/TypographyCatalog.js
=> chore(all): Update design links

src/CheckboxCatalog.js
=> fix(checkbox): Add initially checked and unchecked

src/DrawerCatalog.js, src/frame/DrawerFramePage.js
=> fix(drawer): Fix unintended navigation when clicking drawer links

src/ShapeCatalog.js
=> fix(shape): Resolve errors when leaving page

package-lock.json, package.json, src/frame/DrawerFramePage.js, src/frame/TopAppBarFramePage.js, src/styles/App.scss, src/styles/DrawerFrameCatalog.scss
Adjust styles for top app bar and drawer. 
Update top app bar to 0.35.1.
Replace #2643 fix with #2704 fix for media query.
=> fix(top-app-bar): Adjust styles for top app bar and drawer.

src/ComponentSidebar.js
Resolves scrolling issues with mobile devices.
=> fix(catalog): Add unmount function to sidebar

src/HeaderBar.js, src/styles/HeaderBar.scss
=> Modify header text to be abbreviated in mobile

package-lock.json, package.json, src/SelectCatalog.js
=> feat(select): Add outlined variant

src/styles/CardCatalog.scss
=> fix(card): Remove stale comment and unnecessary import

package-lock.json
#171 had spurious changes to package-lock containing git conflicts. That PR shouldn't have even needed to change that file, so I'm simply reverting the changes to that file.
=> chore: Revert accidental conflict changes to package lock

package-lock.json, package.json, src/ComponentCatalogPanel.js, src/ListCatalog.js, src/SwitchCatalog.js, src/TabsCatalog.js, src/styles/SwitchCatalog.scss, src/styles/TabsCatalog.scss
* Updates tab catalog page to use new mdc-tab-bar
* Updates switch catalog page to use new markup + JS
* Updates some usages of list which conflicted with markup updates
Added one reviewer for each of the bullet points above.
Fixes #174 
Fixes #175
=> Update Catalog for MDC Web 0.38

src/TabsCatalog.js
See https://github.com/material-components/material-components-web/issues/3301 and https://github.com/material-components/material-components-web/pull/3304
=> fix(tab): Use span instead of div inside button

src/TextFieldCatalog.js, src/ThemeCatalog.js
Removes the non-box variant with the new default box variant. 
fixes: #184
=> Update text field demo

src/styles/ComponentPage.scss
Also fixed iOS devices to have momentum scroll on main content.
=> Fixes layout on mobile for demo pages

src/SelectCatalog.js
=> fix(select): Remove --box class and change Box reference to FIlled

src/TextFieldCatalog.js
=> fix(text-field): Don't render mdc-line-ripple for textareas

package-lock.json, package.json, src/ListCatalog.js, src/styles/ListCatalog.scss
=> feat(list): Add checkbox/radio demos to list

src/SelectCatalog.js, src/styles/SelectCatalog.scss
Fixes #217.
Steps to test:
1. Checkout the feat/select-new branch in MDC Web
1. In the catalog checkout, run the mdc-copy-packages script found in https://gist.github.com/kfranqueiro/d06c7073c5012de3edb6c5875d6a4a50
1. Check out this branch and run `npm start`
1. Browse to http://localhost:3000/#/component/select
=> feat(select): Update catalog for drop-down arrow and enhanced select

package-lock.json, package.json, src/SelectCatalog.js, src/styles/SelectCatalog.scss
This is identical to #218, with the addition of package.json + package-lock.json updates and rebased against master.
=> chore: Update to v0.41.0

src/ComponentImageList.js, src/ComponentPage.js, src/SurveyBanner.js, src/styles/App.scss, src/styles/SurveyBanner.scss
=> feat: add web survey banner

package-lock.json, package.json, src/SelectCatalog.js, src/TextFieldCatalog.js, src/ThemeCatalog.js, src/styles/ThemeCatalog.scss
=> feat: Update text field and select pages for notched outline

package-lock.json, package.json, src/ButtonCatalog.js, src/SnackbarCatalog.js, src/styles/SnackbarCatalog.scss
=> chore: Update MDC Web to 0.43.0

src/ComponentCatalogPanel.js, src/styles/ComponentPage.scss, src/styles/ComponentView.scss
Fixes the graphic resize to be centered and removes unused graphic class.
=> Fix graphic resize class

src/SelectCatalog.js, src/TextFieldCatalog.js, src/styles/ComponentCatalogPanel.scss
also moved localConfig from HeroComponent to ComponentCatalogPanel. This allowed me to decouple the HeroOptions component to match the hero.
Still outstanding:
- Fix 100% height of the hero.
- test old hero components
=> new hero  - update layout to match responsive mock up

package-lock.json, package.json, src/ThemeCatalog.js
Also fixes a longer-standing issue of the switches not rendering in the theme page.
Fixes #249.
=> Upgrade to MDC Web 1.0.0

src/IFrameRoutes.js, src/styles/ComponentCatalogPanel.scss
The hero styles were changed with the new catalog panel. This restores those styles under their own class.
=> Fix iframe hero styles
