material-components/material-components-web-catalog

- package-lock.json
- package.json
Set up dependencies for GitHub pages as per [these instructions](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#github-pages).
To deploy to GitHub pages:
1. Run `npm run deploy`
2. Set the GitHub Pages option in project settings to use the `gh-pages` branch.
Fixes #1.
> Set up for GitHub pages

- public/index.html
Adds the font style sheets to the head of the index.html page for users who don't have Roboto installed.
> fix: Add link to fonts used in the demo

- README.md
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
- src/App.js
- src/ComponentPage.js
- src/HeaderBar.js
- src/constants.js
This avoids needing to import every single image individually, which is excessively onerous for demos such as Image List.
Tested with both `npm start` and `npm run build`.
> Use CopyWebpackPlugin to copy images folder

- package-lock.json
- package.json
This repository doesn't represent a readily-consumable npm package, so ostensibly all of its current `dependencies` should actually be listed as `devDependencies`.
> Switch dependencies to devDependencies

- config/webpack.config.dev.js
- config/webpack.config.prod.js
This fixes the checkbox page when built. It was missed in #46.
> fix(checkbox): Add to webpack configs

- config/webpack.config.prod.js
- package-lock.json
- package.json
- src/index.js
- src/registerServiceWorker.js
Earlier we removed the service worker code generated by create-react-app, but we should have in fact swapped out the default import for `unregister` in order to clear it out for anyone who already visited the site.
See https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#opting-out-of-caching
> Restore service worker code in order to remove the cache

- public/index.html
> fix: Add missing font weights for "Roboto"

- src/ComponentCatalogPanel.js
- src/ComponentPage.js
- src/styles/App.scss
- src/styles/ComponentPage.scss
- src/styles/ComponentView.scss
- src/styles/ImageListCatalog.scss
Remove mdc-layout-grid from every component page since we're using drawer for the sidebar.
Also make the demo-content width consistent for every component page.
> Remove layout-grid from every component page

- src/ButtonCatalog.js
- src/CheckboxCatalog.js
- src/ChipsCatalog.js
- src/ComponentCatalogPanel.js
- src/DialogCatalog.js
- src/DrawerCatalog.js
- src/FabCatalog.js
- src/ImageListCatalog.js
- src/LayoutGridCatalog.js
- src/LinearProgressIndicatorCatalog.js
- src/ListCatalog.js
- src/MenuCatalog.js
- src/RadioButtonCatalog.js
- src/RippleCatalog.js
- src/SelectCatalog.js
- src/ShapeCatalog.js
- src/SliderCatalog.js
- src/SnackbarCatalog.js
- src/SwitchCatalog.js
- src/TabsCatalog.js
- src/TextFieldCatalog.js
- src/TopAppBarCatalog.js
Make all demo headings `subtitle1` to align with design. 
Remove levels that no longer exist in MDC Typography, like `subheading2`, `headline`, `title`.
> fix(typography): Make headings consistent

- src/ComponentSidebar.js
Navigating to a route the user is already at causes an error to print in the console because the sidebar tries to push a duplicate entry to the history.
> fix(infrastructure): Error when navigating to route when user is already at that route

- src/ButtonCatalog.js
The `stroked` button has been renamed to `outlined`
> Change Stroked button to Outlined

- src/styles/ComponentPage.scss
Fixes the demo-content overflowing the window.
Fix the demo content from looking like this on small devices...
...to looking like this on small devices...
> Fix overflowing demo content

- src/ComponentImageList.js
- src/ComponentSidebar.js
- src/TabsCatalog.js
This renames "Tabs" to "Tab Bar" in the index, sidebar, and tabs catalog page, in an effort to clarify that it pertains to the new MDC Tab Bar component, not the deprecated MDC Tabs component. This was previously causing some confusion.
This does not rename the route, in an effort to preserve links that already worked.
> fix(tab-bar): Rename Tabs page to Tab Bar to disambiguate

- src/ComponentPage.js
- src/styles/ComponentPage.scss
Removed `translateX` animation on demo content and added `mdc-drawer-app-content` class to set appropriate margin.
> fix(drawer): Fixes scrollbar gets hidden on drawer open issue.

- src/ComponentSidebar.js
Fixes #194.
The issue was somewhat confusing to diagnose due to the fact that we're destroying/reinstantiating the drawer directly in the resize handler (as well as instantiating in initDrawer), and while we are debouncing resize calls, we aren't doing the same for the 225ms timeouts set up within the resize handler. It's possible for multiple 225ms timeouts to be scheduled because the condition for setting them up is still true the next time the debounced resize handler is called (~50ms) but before the first scheduled drawer destruction/instantiation is executed (~175ms left).
The main issue, however, was that the Drawer instantiation inside the resize handler is redundant - updating the state will cause render to be called, which will in turn call initDrawer, which should be the only …
> fix: Avoid pile-up of drawer instantiations

- src/DialogCatalog.js
Refs #200. This updates the existing examples. We will add examples of simple/confirmation dialogs separately.
Note that this currently requires [symlinking](https://gist.github.com/kfranqueiro/d06c7073c5012de3edb6c5875d6a4a50) MDC Web dependencies, since there's no pre-release.
> feat(dialog): Update to 0.40.0 Dialog

- src/DialogCatalog.js
Adds examples from the spec to the dialog page: Alert, Simple, Confirmation, and Scrollable.
> feat(dialog): Add spec examples to catalog page

- README.md
- src/ButtonCatalog.js
- src/CardCatalog.js
- src/CheckboxCatalog.js
- src/ChipsCatalog.js
- src/ComponentCatalogPanel.js
- src/ComponentImageList.js
- src/ComponentSidebar.js
- src/DialogCatalog.js
- src/DrawerCatalog.js
- src/FabCatalog.js
- src/FormField.js
- src/HeaderBar.js
- src/IconButtonCatalog.js
- src/LinearProgressIndicatorCatalog.js
- src/ListCatalog.js
- src/MenuCatalog.js
- src/RadioButtonCatalog.js
- src/RippleCatalog.js
- src/SelectCatalog.js
- src/SliderCatalog.js
- src/SnackbarCatalog.js
- src/SwitchCatalog.js
- src/TabsCatalog.js
- src/TextFieldCatalog.js
- src/ThemeCatalog.js
- src/TopAppBarCatalog.js
- src/frame/DrawerFramePage.js
Currently we have a mix of MDC imports that explicitly reference `index`, explicitly reference `dist/mdc.*.js`, and others that just import the package root.
This PR updates so that everything references `index`, since I already configured our toolchain to process MDC's code through babel back in #43. It saves roughly 17KB in the minified/gzipped JS produced by the build on master, and will save more in future releases when considering that https://github.com/material-components/material-components-web/pull/3245 will change the behavior of package-root imports.
> chore: Explicitly reference index.js under MDC packages

- src/App.js
- src/ButtonCatalog.js
- src/CardCatalog.js
- src/CheckboxCatalog.js
- src/ChipsCatalog.js
- src/DialogCatalog.js
- src/DrawerCatalog.js
- src/ElevationCatalog.js
- src/FabCatalog.js
- src/IFrameRoutes.js
- src/IconButtonCatalog.js
- src/ImageListCatalog.js
- src/LayoutGridCatalog.js
- src/LinearProgressIndicatorCatalog.js
- src/ListCatalog.js
- src/MenuCatalog.js
- src/RadioButtonCatalog.js
- src/RippleCatalog.js
- src/Routes.js
- src/SelectCatalog.js
- src/SliderCatalog.js
- src/SnackbarCatalog.js
- src/SwitchCatalog.js
- src/TabsCatalog.js
- src/TextFieldCatalog.js
- src/TopAppBarCatalog.js
- src/TypographyCatalog.js
This adds routes to just render the hero demo of each component page by itself so we can render the hero section inside of the spec articles as part of an experiment. 
This also creates a `Hero` component for all pages that didn't have one. It also converts the function components to class Hero components.
> feat: Add routes to just render Hero components for material.io experiments

- src/styles/App.scss
- src/styles/ComponentPage.scss
- src/styles/ComponentView.scss
- src/styles/HeroComponent.scss
- src/styles/ListCatalog.scss
- src/styles/SelectCatalog.scss
Adds the list import to the top level App.scss since there were 4 instances included globally (sass files are not route/component specific).
> Remove redundant list imports in multiple bundles

- src/hero/HeroComponent.js
The tabs were refactored and this was missed. The google analytics events are coming in as `tab_clicked_undefined` since the tabPosition prop was removed. The children element passed in is the tab label text.
> Fix tab click event to use label text

- src/constants.js
- src/index.js
Analytics is tracking each variant/label change for the code snippets as separate page views which is tanking our stats. This update tracks the previous path with the current path to ensure we don't register a page view when the user just changed the variant type.
> Fix Analytics

- src/TextFieldCatalog.js
The notched outline should add a `no-label` class when the label is empty or doesn't exist.
> Fix no label for notched outline
